api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Api/Resource'
            - '%kernel.project_dir%/src/Entity'

    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]

    patch_formats:
        json: [ 'application/merge-patch+json' ]

    path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'
    enable_link_security: true

    defaults:
        stateless: false
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
            standard_put: false
            rfc_7807_compliant_errors: true
        operations: [ ]
        pagination_enabled: false
        denormalization_context:
            skip_null_values: false
            groups: [ '__donotmatch__' ]
        normalization_context:
            skip_null_values: false
            groups: [ '__donotmatch__' ]
        collect_denormalization_errors: true
