framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'ChangeMe <changeme@example.com>'

when@test:
    framework:
        mailer:
            message_bus: false
