# Debug Doctrine queries in console commands with -vvv
when@dev:
    monolog:
        handlers:
            console:
                type: console

# Monolog added in testing to keep PHPUnit stdout clean of "Uncaught PHP Exception"
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
