version: "3.4"

services:
  # PostgreSQL Database
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=kit_dev
      - POSTGRES_USER=api-platform
      - POSTGRES_PASSWORD=!ChangeMe!
    ports:
      - "5432:5432"

  # Database Management UI
  adminer:
    image: adminer
    ports:
      - "8090:8080"
    environment:
      ADMINER_DESIGN: 'rmsoft_blue'

  # Redis Cache & Queue (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --loglevel warning

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
